### PR TITLE
Coverity Fix: Close opened mmd libraries

### PR DESCRIPTION
**Pull request by tylerzhao7684**
`Type: Resource leak (RESOURCE_LEAK)`
`mmd_library` is not properly closed under several exit conditions, we need to close it before exiting

### CODE REVIEW

**Comment by tylerzhao7684** [comment]
Seems like the mmd library is accessed globally, need another way to fix this

**Comment by tylerzhao7684** [comment]
Confirmed that it is [this line](https://github.com/intel/fpga-runtime-for-opencl/pull/290/files#diff-19c39c37ac49dd54644d15ef56b292822bfd0b787aabe9bdadeed8154196aa6dR633) that causes the unit test to fail
@zibaiwan Any idea on this?
Coverity doesn't like mmd_library (A pointer) to be lost even though the library is accessed globally

**Comment by tylerzhao7684** [comment]
I looked at https://github.com/intel/fpga-runtime-for-opencl/pull/227 and used a similar method to close the library
Also looked at https://github.com/intel/fpga-runtime-for-opencl/pull/264 and I think it caused a regression because in some cases `dlsym` need to be called on libraries that are opened globally
The current fix allows mmd library to be opened globally as well as automatically be closed when the runtime finishes (This fixes the Coverity case but not https://hsdes.intel.com/appstore/article/#/14018765067)
I'll run l3 to see if this also caused an regression

**Comment by tylerzhao7684** [comment]
This fix is blocked until we remove pac_a10 and pac_s10 boards (At least) in test infra

**Comment by tylerzhao7684** [comment]
@zibaiwan Integration test passed with this implementation
Review please!

**Review by zibaiwan — DISMISSED** [review]

**Comment by zibaiwan** [comment]
@tylerzhao7684 , as we are very close to merge this in. Assuming the window testing passes, could you please squash your 4 commits into 1 commit as they essentially all for fixing one issue?

The configuration in this repo is set to merge all 4 commits into the repo instead of squashing them into 1 automatically, to allow one large PR can have multiple meaningful commits. You can choose the way you like to do the squash, e.g., `rebease -i` or `reset --soft`, and then do a force push. Let me know if you have any questions! 

Thanks you!

**Comment by zibaiwan** [comment]
@tylerzhao7684 , can you please take a look at the workflow failure? My guess is, `cov-errors.txt` is now empty based on the empty output of the `cat cov-errors.txt` because you fixed the last Coverity issue. However, I don't understand why `count=$(grep -c '^$' cov-errors.txt) && echo "$(( $count / 2 ))"` would fail in this case, instead of just outputting `0`.

One possible guess is: `cov-errors.txt` didn't exist and the `grep` failed, but it didn't make sense why `cat cov-errors.txt` didn't fail earlier. Can you please investigate a bit and this PR likely needs a supplement change in the workflow as well, otherwise the main branch workflow will show the failure status.

**Comment by tylerzhao7684** [comment]
This previous workflow didn't fail because #277 was not merged in, so even if this PR fixes one coverity issue, the other one still remain as it is not merged
Here's the previous [workflow run](https://github.com/intel/fpga-runtime-for-opencl/actions/runs/4916197415/jobs/8779637472) 

Now it fails because it couldn't find cov-errors.txt, which is a good sign because now we don't have coverity issues anymore!
I'll work on a small fix in this PR to make this workflow succeed when cov-errors.txt is not found

**Comment by zibaiwan** [comment]
> This previous workflow didn't fail because #277 was not merged in, so even if this PR fixes one coverity issue, the other one still remain as it is not merged Here's the previous [workflow run](https://github.com/intel/fpga-runtime-for-opencl/actions/runs/4916197415/jobs/8779637472)
> 
> Now it fails because it couldn't find cov-errors.txt, which is a good sign because now we don't have coverity issues anymore! I'll work on a small fix in this PR to make this workflow succeed when cov-errors.txt is not found

I am not 100% sure if it indeed failed due to cov-errors.txt is not found, because in the workflow, `cat cov-errors.txt` step didn't fail. I tested it locally on one of the linux machine, this would give an error like this `cat: dummy.txt: No such file or directory`, but maybe the workflow machine has a different linux distribution therefore no error? But if it indeed caused by no file found, I 100% agree this is a good sign!

**Comment by zibaiwan** [comment]
> This previous workflow didn't fail because #277 was not merged in, so even if this PR fixes one coverity issue, the other one still remain as it is not merged Here's the previous [workflow run](https://github.com/intel/fpga-runtime-for-opencl/actions/runs/4916197415/jobs/8779637472)
> 
> Now it fails because it couldn't find cov-errors.txt, which is a good sign because now we don't have coverity issues anymore! I'll work on a small fix in this PR to make this workflow succeed when cov-errors.txt is not found

A separate commit for the workflow fix is more appropriate (no need to squash) but can be merged in the same PR.

**Comment by tylerzhao7684** [comment]
> > This previous workflow didn't fail because #277 was not merged in, so even if this PR fixes one coverity issue, the other one still remain as it is not merged Here's the previous [workflow run](https://github.com/intel/fpga-runtime-for-opencl/actions/runs/4916197415/jobs/8779637472)
> > Now it fails because it couldn't find cov-errors.txt, which is a good sign because now we don't have coverity issues anymore! I'll work on a small fix in this PR to make this workflow succeed when cov-errors.txt is not found
> 
> I am not 100% sure if it indeed failed due to cov-errors.txt is not found, because in the workflow, `cat cov-errors.txt` step didn't fail. I tested it locally on one of the linux machine, this would give an error like this `cat: dummy.txt: No such file or directory`, but maybe the workflow machine has a different linux distribution therefore no error? But if it indeed caused by no file found, I 100% agree this is a good sign!

You are correct, there is a cov-errors.txt. 
The workflow failed because grep returns non-zero exit code when it finds no match, I added the fix now

**Review by zibaiwan — APPROVED** [review]

**Pull request merged**
