### PR TITLE
Add Thread Sanitizer CI/CD

### PR DESCRIPTION
**Pull request by sherry-yuan**
ThreadSanitizer is a tool that detects data races. It consists of a compiler instrumentation module and a run-time library.

This help us to identify race conditions within the program. It will have greater coverage if we can mock MMD.

Addresses #38

### CODE REVIEW

**Comment by sherry-yuan** [comment]
Apparently tsan doesn't work on internal workstations because both the OS and gcc tsan is too old. 
> So the immediate cause of this problem is that the lsan memory allocator in gcc 8 uses a fixed address of 0x600000000000ULL for starting its memory maps.  This is beyond the end of virtual memory for some older kernels (which end at 0x400000000000ULL) but within range for newer ones.

Have to test the flow on using provided images.

**Comment by sherry-yuan** [comment]
Currently this depend on https://github.com/intel/fpga-runtime-for-opencl/issues/71 being fixed for third party libraries, I currently need to focus on a release critical feature before I could get to fixing third party libraries.

**Comment by pcolberg** [comment]
Thanks @sherry-yuan! Small clarification, `acl_threadsupport` is a first-party library.

**Review by pcolberg — APPROVED** [review]

**Comment by sherry-yuan** [comment]
Thanks @pcolberg :)

**Pull request merged**
