### PR TITLE
Pull klocwork images from GitHub package registry

### PR DESCRIPTION
**Pull request by pcolberg**

### CODE REVIEW

**Review by zibaiwan — APPROVED** [review]
Looks good! Thanks!

**Comment by pcolberg** [comment]
The Klocwork workflow is [reproducibly failing to pull the image](https://github.com/intel/fpga-runtime-for-opencl/actions/workflows/klocwork-pull-request.yml?query=branch%3Acov_annotation) from the GitHub package registry in https://github.com/intel/fpga-runtime-for-opencl/pull/22 with `Error response from daemon: unauthorized` even though it worked fine in this pull request. The `-dev` images are being pulled without issues and have the same access permissions as the Klocwork image. :confused:

**Comment by pcolberg** [comment]
Pull request opened by myself with test commit f84274ea18823127cf806bf0fed21978ef52c869 triggering the [Klocwork workflow passed](https://github.com/intel/fpga-runtime-for-opencl/runs/4303790689?check_suite_focus=true). It remains unclear whether the issue persists in other cases, e.g., whether `GITHUB_TOKEN` permissions differ depending on who opens the pull request.

**Comment by pcolberg** [comment]
@sherry-yuan submitted test commit 34817d1f4fc8f818c444346cdbd669a658d4ec8d which also [passed Klocwork workflow](https://github.com/intel/fpga-runtime-for-opencl/runs/4304581113?check_suite_focus=true).

**Pull request merged**
